### ISSUE TITLE
error after `invoke view`: "no idea what view is"

### ISSUE THREAD

**Issue by dmmfll** [Springerle/hovercraft-slides#2]
Hello,

I cloned the hovercraft-slides repo.

I then executed the following:

`. .env --yes && invoke test`

with this output:

```

*** Activated .venv/hovercraft-slides
Cleaning up project files
/bin/sh: 1: .: .env: not found
```
And then I tried:

```
invoke view

```
with this output:

```

No idea what 'view' is!

```

I must be missing some thing simple. Ideas? Thank you in advance.

operating system info:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Comment by jhermann** [comment]
Worked with Python 3.6.2 after upgrading dependencies (seems they were too old, at least for 3.6.x).
